import{S as l,N as d,P as u,a as f,i as p,R as m}from"./assets/vendor-W7YMlJGr.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(r){if(r.ep)return;r.ep=!0;const a=s(r);fetch(r.href,a)}})();const g=document.querySelector("[data-menu-open]"),y=document.querySelector("[data-menu-close]"),o=document.querySelector("[data-menu]");function b(){o.classList.add("is-open"),document.body.classList.add("no-scroll")}function c(){o.classList.remove("is-open"),document.body.classList.remove("no-scroll")}g.addEventListener("click",b);y.addEventListener("click",c);o.addEventListener("click",t=>{t.target===o&&c()});const h="https://furniture-store.b.goit.study/api/feedbacks";function w(t){const e=parseFloat(t);return e>=3.3&&e<=3.7?3.5:e>=3.8&&e<=4.2?4:e}async function v(){try{const t=await f.get(h,{params:{page:"1",limit:"10"}}),e=Array.isArray(t.data)?t.data:t.data.feedbacks;return console.log(e),e}catch(t){return console.log(t),p.error({message:"Failed to load feedbacks",position:"topRight",titleColor:"red"}),[]}}function L(t){return t.map(({name:e,descr:s,rate:n})=>`
      <li class="swiper-slide feedback-item">
        <div class="feedback-card">
          <div class="star-rating-container" data-rating="${w(n)}"></div>
          
          <p class="feedback-comment">"${s}"</p>
          <h3 class="feedback-user-name">${e}</h3>
        </div>
      </li>
    `).join("")}function k(){document.querySelectorAll(".star-rating-container").forEach(e=>{const s=parseFloat(e.getAttribute("data-rating"));new m(e,{score:s,readOnly:!0,half:!0,halfShow:!0,starType:"i",starOn:"fas fa-star",starOff:"far fa-star",starHalf:"fas fa-star-half-alt",space:!1}).init()})}async function P(){const t=document.querySelector(".feedback-list");if(!t)return;const e=await v();e.length!==0&&(t.innerHTML=L(e),k(),new l(".feedback-swiper",{modules:[d,u],slidesPerView:1,spaceBetween:20,pagination:{el:".feedback-dots",clickable:!0,renderBullet:s=>`<li class="${s}"></li>`},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{768:{slidesPerView:2,spaceBetween:32},1440:{slidesPerView:3,spaceBetween:32}}}))}P();
//# sourceMappingURL=index.js.map
